[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/.cache/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
[[context.deploy-preview.plugins]]
package = "/plugins/cypress"